version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
        - typescript
  eslint:
    enabled: true
    channel: "eslint-7"
    config:
      extensions:
        - tsx
  fixme:
    enabled: true
ratings:
  paths:
    - "**.ts"
exclude_paths:
  - __tests__/
  - examples/
  - docs/
  - .yarn
  - coverage
  - .github
  - .vscode
